services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "${PORT_WP}:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
    volumes:
      - ./${INSTANCE_NAME:-wp_instance}/wordpress:/var/www/html
      - ./${INSTANCE_NAME:-wp_instance}/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - wpnet

  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - ./${INSTANCE_NAME:-wp_instance}/mysql:/var/lib/mysql
    networks:
      - wpnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PORT_PMA}:80"
    environment:
      PMA_HOST: ${WORDPRESS_DB_HOST:-db}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    networks:
      - wpnet

networks:
  wpnet:
    driver: bridge